### ISSUE TITLE
nice project

### ISSUE THREAD

**Issue by weepy** [jdavidw13/jquery-binddata#1]
similar to my project, but more concentrated: 

http://github.com/weepy/o_O

any plans for further functionality ?

**Comment by jdavidw13** [comment]
The story is, we had some very inexperienced developers start a jquery mobile application before myself and some others were brought in to help finish it.  With deadlines quickly approaching, there was no time to refactor the application and use one of the many MVC frameworks out there.  This plugin is an abstraction of some code I wrote for one of the more complex forms we had in the app.

Basically, this is all that logic, plus some stuff I wish I had when originally working on that form.  I was thinking about possibly adding binding to the model so that the form would be updated on change, but I've really just started throwing this together.  Btw, I love funnyface, looks pretty awesome!

---

 From: weepy reply@reply.github.com
To: jdavidw13 jdavidw13@yahoo.com 
Sent: Tuesday, July 31, 2012 2:53 PM
Subject: [jquery-binddata] nice project (#1)

similar to my project, but more concentrated: 

http://github.com/weepy/o_O

any plans for further functionality ?

---

Reply to this email directly or view it on GitHub:
https://github.com/jdavidw13/jquery-binddata/issues/1

**Comment by rafaelmotta** [comment]
I was writing a pluging like this, but I found yours before.. so I decided to use. I made some changes bacause I found some issues. During the week I gonna send u what I have changed.

**Comment by jdavidw13** [comment]
I saw your changes and merged them into master.  I totally forgot about hidden elements.
